### ISSUE TITLE
Weird crash 1.8.9

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#38]
[crash-2022-11-10_04.46.04-client.txt](https://github.com/AxolotlClient/AxolotlClient-mod/files/9974994/crash-2022-11-10_04.46.04-client.txt)

**Comment by moehreag** [comment]
This is caused by us manually adding log4j in the dev environment because it likes to break there randomly. Since this pulls in the newest version there is a single method that didn't yet exist in the old version Minecraft uses by default.
There are two possible ways to solve this:

* adding a patch file in MMC/Prismlauncher to force-update log4j (we have one already, but not at hand right now.)
* wait until we fix that with a commit in the next few days.

**Comment by moehreag** [comment]
fixed in https://github.com/AxolotlClient/AxolotlClient-mod/commit/2a4cd019ca3a108e62a9a98bf05b9957e152a4ce

**Comment by HowardZHY** [comment]
plz release the fix to download it

**Comment by moehreag** [comment]
https://github.com/AxolotlClient/AxolotlClient-mod/suites/9265111565/artifacts/433785201

Otherwise will probably create a release later today or tomorrow.

**Comment by HowardZHY** [comment]
thanks



At 2022-11-12 21:59:27, "moehreag" ***@***.***> wrote:

https://github.com/AxolotlClient/AxolotlClient-mod/suites/9265111565/artifacts/433785201

Otherwise will probably create a release later today or tomorrow.

**Comment by HowardZHY** [comment]
damn the jar from artifacts still crashes. same error. 
[crash-2022-11-10_04.46.04-client.txt](https://github.com/AxolotlClient/AxolotlClient-mod/files/9995409/crash-2022-11-10_04.46.04-client.txt)

**Comment by moehreag** [comment]
yes, though that's because of the config lib (had already been fixed, just not updated.)
Pushed a commit doing that now, otherwise it's on our maven if you want it that way.
